FROM node:20.16.0-alpine3.19

RUN mkdir /etc/http_server.d 

WORKDIR /etc/http_server.d 

RUN apk update \
    && apk add --no-cache python3 py3-pip \
# Install essential packages for RPC
    && npm install serialize-javascript \
# user package
    && npm install @zerodep/string-padleft

RUN rm -rf /var/cache/apk/*

ADD http_server.tar /etc/http_server.d

EXPOSE 30109
# Our server startup shell script
CMD [ "./startup.sh" ]
